### PR TITLE
WIP Function ´implicit_restart!´ now uses  Givens rotations

### PR DESCRIPTION
**Pull request by NymanLauri**

### CODE REVIEW

**Comment by haampie** [comment]
Seems like the Given's rotation tests is missing?

**Comment by NymanLauri** [comment]
"test/givens_rotation.jl" in "Fix the tests" commit, isn't that the one?

**Comment by haampie** [comment]
Oh right, I somehow missed it.

**Comment by haampie** [comment]
Just merging it, since the whole repo is still WIP anyways!

**Pull request merged**
